M48
; DRILL file {KiCad (6.0.0)} date Sun Jul 31 17:47:10 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-31T17:47:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.1752Y-3.1994
X4.1752Y-4.8747
X7.4823Y-4.8704
X7.4833Y-3.1951
T0
M30
