M48
; DRILL file {KiCad (6.0.0)} date Sun Jul 31 18:03:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-31T18:03:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.9378Y-3.7154
X4.2116Y-2.3213
X4.9877Y-2.3213
X6.2717Y-3.7154
T0
M30
