M48
; DRILL file {KiCad (6.0.0)} date Tue Jul 19 20:58:09 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-19T20:58:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.8327Y-4.3809
X2.8327Y-6.1998
X6.6722Y-6.1998
X6.6732Y-4.3809
T0
M30
