M48
; DRILL file {KiCad (6.0.0)} date Sun Jul 31 17:52:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-31T17:52:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.5817Y-5.6033
X3.4222Y-4.1821
X6.838Y-4.1821
X7.6799Y-5.6033
T0
M30
